name: Compile LaTeX document
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex

      - name: Convert PDF to PNG
        run: |
          sudo apt-get install -y poppler-utils
          pdftoppm cv.pdf output -png -rx 150 -ry 150
          mv output-1.png README.png

      - name: Commit and push generated files
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.png
          git commit -m "Update README.png" || exit 0
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git push HEAD:${{ github.ref }}